public without sharing class RestStringUtil {
  public static final String ID_PARAM = 'id';
  public static final String TODO = 'TODO';
  public static final String SERVER_SIDE_EXCEPTION_MSG = 'Salesforce has hit an uncaught exception: ';
  public static final String INVALID_AUTHENTICATION_MSG = 'Authorization is invalid';
  public static final String INVALID_PARAMS_MSG = 'Please use an Id param';
  public static final String INVALID_ENDPOINT_MSG = 'Invalid Endpoint';
}
